name: flutter_riverpod_example
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # riverpod
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # http
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints and generators
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

  # models
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true